name: Stats compiler
on:
  schedule:
    - cron:  '0 5,11,17,23 * * *'
jobs:
  stats-compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt install flatpak-builder
          pip install requests
      - name: Put in current directory fp-stats tools
        run: |
          git clone https://github.com/lionirdeadman/fp-stats
          mv fp-stats/* .
      - name: Flathub clone
        run: python3 flathub-application-cloner.py
      - name: Compile runtime version information
        run: python3 flathub-runtime-information-compiler.py
      - name: Compile architecture information
        run: python3 flathub-architecture-information-compiler.py
      - name: Git push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add runtime_arch_information/
          git add runtime_version_information/
          if ! git diff --staged --quiet; then git commit -m "Data bump" && git push; fi
