name: Stats compiler test
on: workflow_dispatch
jobs:
  stats-compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt install flatpak-builder
          pip install requests
      - name: Put in current directory fp-stats tools
        run: |
          git clone https://github.com/lionirdeadman/fp-stats
          mv fp-stats/* .
      - name: Flathub clone & compile
        run: |
          python3 flathub-application-cloner.py
          python3 flathub-architecture-information-compiler.py
          python3 flathub-runtime-information-compiler.py
      - name: Git push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "runtime_arch_information/*"
          git add "runtime_version_information/*"
          git commit -m "Data bump"
          git push
